#.cargo/config.toml
[build]
target-dir = "target"
incremental = true

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true

[target.x86_64-unknown-linux-gnu]
linker = "cc"

[unstable]
build-std = ["std", "panic_abort"]

[alias]
test-fast = "nextest run"
coverage = "llvm-cov --html --output-dir coverage/html"
